import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, Image as ImageIcon, Zap, AlertTriangle, Wifi, WifiOff, Lock, LayoutTemplate, Code, HelpCircle, X, Server, Settings, History, Brain, Copy, Check, Lightbulb, BookOpen, Wrench, Download, ArrowRight } from 'lucide-react';
import SettingsPanel from './components/SettingsPanel';
import HistoryGallery from './components/HistoryGallery';
import PromptBuilder from './components/PromptBuilder';
import PromptArea from './components/PromptArea';
import MobileDrawer from './components/MobileDrawer';
import AIAssistant from './components/AIAssistant';
import LanguageSwitcher from './components/LanguageSwitcher';
import { useLanguage } from './contexts/LanguageContext';
import { GenerationStatus, GeneratedImage, GenerationSettings, CharacterPrompt, GeneralPrompt } from './types';
import { DEFAULT_SETTINGS, COMFY_API_URL } from './constants';
import {
  queueGeneration,
  checkGenerationStatus,
  checkGenerationStatusDetailed,
  getQueueStatus,
  QueueStatus,
  queueGenerationWithUpscale,
  checkUpscaleGenerationStatus,
  uploadImageToComfy,
  queueUpscaleOnly,
  checkUpscaleOnlyStatus
} from './services/comfyService';

type ServerStatusType = 'online' | 'offline' | 'cors_error' | 'checking';

// 维护模式配置
const MAINTENANCE_MODE = false; // 设为 true 开启维护模式
const MAINTENANCE_PASSWORD = "King2647.114514WP";

const App: React.FC = () => {
  const { t } = useLanguage();

  // 维护模式状态
  const [isUnlocked, setIsUnlocked] = useState(() => {
    return localStorage.getItem('newbie_maintenance_unlocked') === 'true';
  });
  const [passwordInput, setPasswordInput] = useState('');
  const [passwordError, setPasswordError] = useState(false);

  // 维护模式页面
  if (MAINTENANCE_MODE && !isUnlocked) {
    return (
      <div className="min-h-screen bg-darker flex items-center justify-center p-4">
        <div className="text-center max-w-md">
          <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6">
            <Wrench size={40} className="text-primary" />
          </div>
          <h1 className="text-2xl font-bold text-white mb-2">{t.maintenance.title}</h1>
          <p className="text-gray-400 mb-6">{t.maintenance.message}</p>
          <div className="space-y-3">
            <input
              type="password"
              placeholder={t.maintenance.passwordPlaceholder}
              value={passwordInput}
              onChange={(e) => {
                setPasswordInput(e.target.value);
                setPasswordError(false);
              }}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  if (passwordInput === MAINTENANCE_PASSWORD) {
                    setIsUnlocked(true);
                    localStorage.setItem('newbie_maintenance_unlocked', 'true');
                  } else {
                    setPasswordError(true);
                  }
                }
              }}
              className={`w-full bg-surface border rounded-lg px-4 py-3 text-white text-center focus:outline-none focus:border-primary transition-colors ${passwordError ? 'border-red-500' : 'border-white/10'
                }`}
            />
            {passwordError && (
              <p className="text-red-400 text-sm">{t.maintenance.wrongPassword}</p>
            )}
          </div>
        </div>
      </div>
    );
  }

  // State
  const [activeTab, setActiveTab] = useState<'builder' | 'raw'>(() => {
    const saved = localStorage.getItem('newbie_activeTab');
    return (saved === 'raw' || saved === 'builder') ? saved : 'builder';
  });
  const [prompt, setPrompt] = useState<string>(''); // The final prompt sent to server
  const [builderOutput, setBuilderOutput] = useState<string>(''); // Prompt generated by builder
  const [rawPrompt, setRawPrompt] = useState<string>(() => {
    return localStorage.getItem('newbie_rawPrompt') || '';
  }); // Independent prompt for raw/advanced mode

  // History preview state
  const [previewingHistoryPrompt, setPreviewingHistoryPrompt] = useState<string | null>(null); // Prompt from clicked history image
  const [selectedHistoryId, setSelectedHistoryId] = useState<string | null>(null); // ID of selected history image

  // Mobile UI State
  const [showMobileSettings, setShowMobileSettings] = useState(false);
  const [showMobileHistory, setShowMobileHistory] = useState(false);

  // AI Prompt Modal
  const [showAIPromptModal, setShowAIPromptModal] = useState(false);
  const [copiedAIPrompt, setCopiedAIPrompt] = useState(false);

  // AI Assistant
  const [showAIAssistant, setShowAIAssistant] = useState(false);

  // Default values for builder
  const DEFAULT_CHARACTERS: CharacterPrompt[] = [{
    id: Date.now().toString(),
    n: 'original_character',
    gender: '1girl',
    appearance: 'grey_hair, medium_hair, middle_part, hair_over_eyes, wavy_ends, slender_eyes, red_eyes, big_breasts, long_legs, blue_earrings, nail_polish, nail_art, blue_nails',
    clothing: 'jacket, necktie, shorts, skirt, fingerless_gloves, boots, white_thighhighs, torn_thighhighs, torn_clothes, thigh_strap, asymmetrical_legwear, mismatched_legwear',
    expression: 'smile, confident',
    action: 'looking_at_viewer, standing, solo',
    position: '',
  }];
  const DEFAULT_GENERAL: GeneralPrompt = {
    count: '1girl, solo',
    style: 'anime_style, digital_art, [AGM86997980], [ciloranko], [wlop], [dishwasher1910], [meion], (kuroduki \\(pieat\\)), [kousaki], [ask (askzy)], [Liduke], (realistic:1), (flat color:2), (haiz ai:1), (no lineart:1), (no outline:1), (Flat vector:1)',
    background: 'simple_background',
    lighting: '',
    atmosphere: '',
    quality: 'HDR, 8K, masterpiece, best quality, amazing quality, very aesthetic, extreme aesthetic, detailed eyes, sharp eyes, newest, highres, absurdres, incredibly absurdres, very awa, detailed backgroud, finished, overlapping, appropriate posture, appropriate configuration, cropping, thick dense skin, ultra-precise skin, soft cheeks',
    objects: '',
    other: '',
    caption: 'A girl wearing a jacket paired with a necktie, shorts and a skirt, along with boots. Her white thighhighs are torn and asymmetrical, and she wears fingerless gloves revealing blue nail polish. Her signature grey medium hair covers her eyes partially, her slender red eyes look at you, and she has a confident smile.',
  };

  // Builder state (lifted up to persist across tab switches)
  const [characters, setCharacters] = useState<CharacterPrompt[]>(() => {
    const saved = localStorage.getItem('newbie_characters');
    return saved ? JSON.parse(saved) : DEFAULT_CHARACTERS;
  });
  const [general, setGeneral] = useState<GeneralPrompt>(() => {
    const saved = localStorage.getItem('newbie_general');
    if (saved) {
      const parsed = JSON.parse(saved);
      // 兼容旧版本：确保 lighting 字段存在
      return { ...DEFAULT_GENERAL, ...parsed };
    }
    return DEFAULT_GENERAL;
  });
  const [settings, setSettings] = useState<GenerationSettings>(() => {
    const saved = localStorage.getItem('newbie_settings');
    return saved ? JSON.parse(saved) : DEFAULT_SETTINGS;
  });
  const [status, setStatus] = useState<GenerationStatus>(GenerationStatus.IDLE);
  const [currentImage, setCurrentImage] = useState<string | null>(null);
  const [history, setHistory] = useState<GeneratedImage[]>([]);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  // Server Status State
  const [serverStatus, setServerStatus] = useState<ServerStatusType>('checking');
  const [mixedContentWarning, setMixedContentWarning] = useState<boolean>(false);
  const [showHelpModal, setShowHelpModal] = useState<boolean>(false);
  const [queueStatus, setQueueStatus] = useState<QueueStatus | null>(null);

  // Upscale State
  const [upscalingId, setUpscalingId] = useState<string | null>(null); // 正在放大的图片 ID

  // Refs for polling
  const pollInterval = useRef<number | null>(null);
  const queuePollInterval = useRef<number | null>(null);
  const upscalePollInterval = useRef<number | null>(null);

  // Check Mixed Content and Server Status on Mount
  useEffect(() => {
    // 1. Check Protocol Mismatch
    const isPageHttps = window.location.protocol === 'https:';
    const isApiHttp = COMFY_API_URL.startsWith('http://');

    if (isPageHttps && isApiHttp) {
      setMixedContentWarning(true);
      // We don't necessarily error out immediately, but we warn heavily
    }

    // 2. Check Server Connectivity with detailed diagnostics
    const checkServer = async () => {
      setServerStatus(prev => prev === 'online' ? 'online' : 'checking');
      try {
        // Try standard fetch first
        const res = await fetch(`${COMFY_API_URL}/system_stats`, { method: 'GET' });
        if (res.ok) {
          setServerStatus('online');
          if (mixedContentWarning) setMixedContentWarning(false); // If it works, maybe user has a proxy or local setup that works
        } else {
          setServerStatus('offline');
        }
      } catch (e) {
        // If standard fetch failed, it could be network error OR CORS.
        // We try a 'no-cors' request. If this DOESN'T throw, the server is reachable but blocked by browser policy.
        try {
          await fetch(`${COMFY_API_URL}/system_stats`, { mode: 'no-cors' });
          setServerStatus('cors_error');
        } catch (e2) {
          // If even no-cors failed, the server is truly unreachable (or SSL error if https)
          setServerStatus('offline');
        }
        console.error("Server check failed details:", e);
      }
    };

    checkServer();
    const interval = setInterval(checkServer, 10000); // Check every 10s
    return () => clearInterval(interval);
  }, [mixedContentWarning]);

  // Poll queue status when server is online
  useEffect(() => {
    if (serverStatus !== 'online') {
      setQueueStatus(null);
      return;
    }

    const fetchQueueStatus = async () => {
      const status = await getQueueStatus();
      setQueueStatus(status);
    };

    fetchQueueStatus();
    queuePollInterval.current = window.setInterval(fetchQueueStatus, 3000); // Every 3s

    return () => {
      if (queuePollInterval.current) {
        clearInterval(queuePollInterval.current);
      }
    };
  }, [serverStatus]);

  // Load history from local storage
  useEffect(() => {
    const saved = localStorage.getItem('newbie_history');
    if (saved) {
      const parsedHistory = JSON.parse(saved);
      // 只保留最近 3 天的历史记录
      const threeDaysAgo = Date.now() - 3 * 24 * 60 * 60 * 1000;
      const filteredHistory = parsedHistory.filter((img: GeneratedImage) =>
        img.timestamp > threeDaysAgo
      );
      setHistory(filteredHistory);
      // 如果过滤掉了一些记录，更新存储
      if (filteredHistory.length < parsedHistory.length) {
        localStorage.setItem('newbie_history', JSON.stringify(filteredHistory));
      }
    }

    // 页面加载时立即检查是否有待处理任务，先禁用按钮
    const pendingTask = localStorage.getItem('newbie_pending_task');
    if (pendingTask) {
      try {
        const task = JSON.parse(pendingTask);
        // 超过 2 小时的任务不再恢复
        if (Date.now() - task.timestamp <= 2 * 60 * 60 * 1000) {
          setStatus(GenerationStatus.QUEUED); // 先设为排队状态，禁用按钮
        } else {
          localStorage.removeItem('newbie_pending_task');
        }
      } catch (e) {
        localStorage.removeItem('newbie_pending_task');
      }
    }
  }, []);

  // 恢复未完成的任务（等服务器在线后开始轮询）
  // 如果服务器离线且任务已超过 5 分钟，自动清理以允许用户重新生成
  useEffect(() => {
    const pendingTask = localStorage.getItem('newbie_pending_task');
    if (!pendingTask) return;

    // 服务器离线时的处理
    if (serverStatus === 'offline' || serverStatus === 'cors_error') {
      try {
        const task = JSON.parse(pendingTask);
        // 如果任务已经超过 5 分钟且服务器离线，清理任务让用户可以重新生成
        if (Date.now() - task.timestamp > 5 * 60 * 1000) {
          localStorage.removeItem('newbie_pending_task');
          setStatus(GenerationStatus.IDLE);
          setErrorMsg(t.status.connectionLost || '连接丢失，请重新生成');
        }
      } catch (e) {
        localStorage.removeItem('newbie_pending_task');
        setStatus(GenerationStatus.IDLE);
      }
      return;
    }

    // 服务器正在检查连接中，不做任何操作
    if (serverStatus !== 'online') return;

    try {
      const task = JSON.parse(pendingTask);
      const { promptId, timestamp, prompt: taskPrompt, width, height, seed } = task;

      // 超过 2 小时的任务不再恢复
      if (Date.now() - timestamp > 2 * 60 * 60 * 1000) {
        localStorage.removeItem('newbie_pending_task');
        setStatus(GenerationStatus.IDLE);
        return;
      }

      // 开始恢复轮询
      setStatus(GenerationStatus.GENERATING);

      const checkPendingTask = async () => {
        try {
          const result = await checkGenerationStatusDetailed(promptId);

          if (result.status === 'not_found') {
            // 任务不存在（ComfyUI 重启后丢失）
            localStorage.removeItem('newbie_pending_task');
            setStatus(GenerationStatus.IDLE);
            setErrorMsg(t.status.taskLost);
            return;
          }

          if (result.status === 'completed') {
            // 任务已完成
            setCurrentImage(result.imageUrl);
            setStatus(GenerationStatus.COMPLETE);
            localStorage.removeItem('newbie_pending_task');

            // 添加到历史（使用回调检查是否已存在）
            const newEntry: GeneratedImage = {
              id: promptId,
              url: result.imageUrl,
              prompt: taskPrompt,
              timestamp: timestamp,
              width: width || 832,
              height: height || 1216,
              seed: seed || -1
            };
            setHistory(prev => {
              if (prev.some(h => h.id === promptId)) return prev;
              return [newEntry, ...prev];
            });
          } else if (result.status === 'pending') {
            // 任务还在进行中，继续轮询
            let attempts = 0;
            const maxAttempts = 4800; // 2小时超时

            pollInterval.current = window.setInterval(async () => {
              attempts++;
              if (attempts > maxAttempts) {
                if (pollInterval.current) clearInterval(pollInterval.current);
                setStatus(GenerationStatus.ERROR);
                setErrorMsg(t.status.taskTimeout);
                localStorage.removeItem('newbie_pending_task');
                return;
              }

              const pollResult = await checkGenerationStatusDetailed(promptId);

              if (pollResult.status === 'not_found') {
                // 任务丢失
                if (pollInterval.current) clearInterval(pollInterval.current);
                localStorage.removeItem('newbie_pending_task');
                setStatus(GenerationStatus.IDLE);
                setErrorMsg(t.status.taskLost);
                return;
              }

              if (pollResult.status === 'completed') {
                if (pollInterval.current) clearInterval(pollInterval.current);
                setCurrentImage(pollResult.imageUrl);
                setStatus(GenerationStatus.COMPLETE);
                localStorage.removeItem('newbie_pending_task');

                // 添加到历史（使用回调检查是否已存在）
                const newEntry: GeneratedImage = {
                  id: promptId,
                  url: pollResult.imageUrl,
                  prompt: taskPrompt,
                  timestamp: timestamp,
                  width: width || 832,
                  height: height || 1216,
                  seed: seed || -1
                };
                setHistory(prev => {
                  if (prev.some(h => h.id === promptId)) return prev;
                  return [newEntry, ...prev];
                });
              }
            }, 1500);
          }
        } catch (e) {
          // 查询失败，可能 ComfyUI 重启了
          localStorage.removeItem('newbie_pending_task');
          setStatus(GenerationStatus.IDLE);
        }
      };

      checkPendingTask();
    } catch (e) {
      localStorage.removeItem('newbie_pending_task');
    }
  }, [serverStatus]);

  // Save history
  useEffect(() => {
    localStorage.setItem('newbie_history', JSON.stringify(history));
  }, [history]);

  // 预加载最近 10 张图片（提升切换性能）
  useEffect(() => {
    const imagesToPreload = history.slice(0, 10);
    imagesToPreload.forEach(img => {
      const image = new Image();
      image.src = img.url;
    });
  }, [history]);

  // Save builder state
  useEffect(() => {
    localStorage.setItem('newbie_characters', JSON.stringify(characters));
  }, [characters]);

  useEffect(() => {
    localStorage.setItem('newbie_general', JSON.stringify(general));
  }, [general]);

  // Save settings
  useEffect(() => {
    localStorage.setItem('newbie_settings', JSON.stringify(settings));
  }, [settings]);

  // Save rawPrompt and activeTab
  useEffect(() => {
    localStorage.setItem('newbie_rawPrompt', rawPrompt);
  }, [rawPrompt]);

  useEffect(() => {
    localStorage.setItem('newbie_activeTab', activeTab);
  }, [activeTab]);

  // Sync prompt based on active tab
  useEffect(() => {
    if (activeTab === 'builder') {
      setPrompt(builderOutput);
    } else {
      setPrompt(rawPrompt);
    }
  }, [builderOutput, rawPrompt, activeTab]);

  // Initialize rawPrompt with builderOutput when switching to raw mode (if rawPrompt is empty)
  useEffect(() => {
    if (activeTab === 'raw' && !rawPrompt && builderOutput) {
      setRawPrompt(builderOutput);
    }
  }, [activeTab]);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    if (mixedContentWarning) {
      alert(t.serverDiag.corsMessage);
      return;
    }

    if (serverStatus !== 'online') {
      setShowHelpModal(true);
      return;
    }

    setStatus(GenerationStatus.PREPARING);
    setErrorMsg(null);
    setCurrentImage(null);

    // 根据是否启用放大选择不同的工作流
    const useUpscale = settings.enableUpscale;

    try {
      // 0. 检查队列是否已满
      const currentQueue = await getQueueStatus();
      if (currentQueue && (currentQueue.queueRunning + currentQueue.queuePending) >= 70) {
        setStatus(GenerationStatus.IDLE);
        setErrorMsg(t.status.serverBusy);
        return;
      }

      // 1. Queue Prompt (根据设置选择工作流)
      setStatus(GenerationStatus.QUEUED);
      const promptId = useUpscale
        ? await queueGenerationWithUpscale(prompt, settings)
        : await queueGeneration(prompt, settings);

      // 保存待处理任务，以便用户关闭网页后恢复
      const pendingTask = {
        promptId,
        timestamp: Date.now(),
        prompt: prompt,
        width: settings.width,
        height: settings.height,
        seed: settings.seed,
        useUpscale // 记录是否使用放大工作流
      };
      localStorage.setItem('newbie_pending_task', JSON.stringify(pendingTask));

      // 2. Poll for Status
      setStatus(GenerationStatus.GENERATING);

      let attempts = 0;
      const maxAttempts = 4800; // 2小时超时 (4800 × 1.5秒 = 7200秒)
      let completed = false;

      pollInterval.current = window.setInterval(async () => {
        if (completed) return;

        attempts++;
        if (attempts > maxAttempts) {
          if (pollInterval.current) clearInterval(pollInterval.current);
          setStatus(GenerationStatus.ERROR);
          setErrorMsg(t.status.generationTimeout);
          localStorage.removeItem('newbie_pending_task');
          return;
        }

        // 根据工作流类型使用不同的状态检查函数
        const imageUrl = useUpscale
          ? await checkUpscaleGenerationStatus(promptId)
          : await checkGenerationStatus(promptId);

        if (imageUrl && !completed) {
          completed = true;
          if (pollInterval.current) clearInterval(pollInterval.current);
          setCurrentImage(imageUrl);
          setStatus(GenerationStatus.COMPLETE);
          localStorage.removeItem('newbie_pending_task');

          // Add to history
          const newEntry: GeneratedImage = {
            id: promptId,
            url: imageUrl,
            prompt: prompt,
            timestamp: Date.now(),
            width: settings.width,
            height: settings.height,
            seed: settings.seed,
            isUpscaled: useUpscale // 标记是否已放大
          };
          setHistory(prev => [newEntry, ...prev]);
        }
      }, 1500);

    } catch (err: any) {
      setStatus(GenerationStatus.ERROR);
      let message = err.message || t.status.connectionFailed;
      if (message.includes("Failed to fetch")) {
        message = t.status.connectionFailed;
      }
      setErrorMsg(message);
      localStorage.removeItem('newbie_pending_task');
      if (pollInterval.current) clearInterval(pollInterval.current);
    }
  };

  // 单独放大已有图片
  const handleUpscaleImage = async (img: GeneratedImage) => {
    if (upscalingId || serverStatus !== 'online') return;

    setUpscalingId(img.id);

    try {
      // 1. 上传图片到 ComfyUI
      const uploadedFilename = await uploadImageToComfy(img.url);

      // 2. 提交放大任务
      const promptId = await queueUpscaleOnly(uploadedFilename, img.prompt, settings.negativePrompt);

      // 3. 轮询等待完成
      let attempts = 0;
      const maxAttempts = 4800; // 2小时超时
      let completed = false;

      upscalePollInterval.current = window.setInterval(async () => {
        if (completed) return;

        attempts++;
        if (attempts > maxAttempts) {
          if (upscalePollInterval.current) clearInterval(upscalePollInterval.current);
          setUpscalingId(null);
          setErrorMsg(t.history.upscaleFailed);
          return;
        }

        const imageUrl = await checkUpscaleOnlyStatus(promptId);

        if (imageUrl && !completed) {
          completed = true;
          if (upscalePollInterval.current) clearInterval(upscalePollInterval.current);
          setUpscalingId(null);

          // 添加放大后的图片到历史记录
          const newEntry: GeneratedImage = {
            id: promptId,
            url: imageUrl,
            prompt: img.prompt,
            timestamp: Date.now(),
            width: img.width * 2, // 放大后尺寸约为 2x
            height: img.height * 2,
            seed: img.seed,
            isUpscaled: true,
            originalId: img.id
          };
          setHistory(prev => [newEntry, ...prev]);

          // 显示放大后的图片
          setCurrentImage(imageUrl);
        }
      }, 1500);

    } catch (err: any) {
      setUpscalingId(null);
      setErrorMsg(t.history.upscaleFailed + ': ' + (err.message || ''));
    }
  };

  const renderServerStatus = () => {
    const totalQueue = queueStatus ? queueStatus.queueRunning + queueStatus.queuePending : 0;

    switch (serverStatus) {
      case 'online':
        return (
          <div className="flex items-center gap-1 sm:gap-2">
            <span className="flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-1 rounded-full bg-green-500/10 text-green-400 text-xs border border-green-500/20 cursor-help" onClick={() => setShowHelpModal(true)}>
              <Wifi size={12} />
              <span className="hidden sm:inline">{t.nav.serverOnline}</span>
            </span>
            {queueStatus && totalQueue > 0 && (
              <span className="flex items-center gap-1 sm:gap-1.5 px-1.5 sm:px-2 py-1 rounded-full bg-orange-500/10 text-orange-400 text-xs border border-orange-500/20" title={`Running: ${queueStatus.queueRunning}, Pending: ${queueStatus.queuePending}`}>
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-orange-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-orange-500"></span>
                </span>
                <span className="hidden sm:inline">{t.nav.queue}</span> {totalQueue}
              </span>
            )}
          </div>
        );
      case 'cors_error':
        return (
          <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-yellow-500/10 text-yellow-400 text-xs border border-yellow-500/20 cursor-pointer hover:bg-yellow-500/20 transition-colors" onClick={() => setShowHelpModal(true)}>
            <AlertTriangle size={12} />
            {t.nav.corsError}
          </span>
        );
      case 'offline':
      default:
        return (
          <span className="flex items-center gap-2 px-3 py-1 rounded-full bg-red-500/10 text-red-400 text-xs border border-red-500/20 cursor-pointer hover:bg-red-500/20 transition-colors" onClick={() => setShowHelpModal(true)}>
            <WifiOff size={12} />
            {t.nav.serverOffline}
          </span>
        );
    }
  };

  return (
    <div className="min-h-screen bg-darker text-gray-100 font-sans selection:bg-primary/30">

      {/* Help Modal */}
      {showHelpModal && (
        <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4" onClick={() => setShowHelpModal(false)}>
          <div className="bg-surface border border-white/10 rounded-2xl max-w-lg w-full p-6 shadow-2xl relative" onClick={e => e.stopPropagation()}>
            <button className="absolute top-4 right-4 text-gray-400 hover:text-white" onClick={() => setShowHelpModal(false)}>
              <X size={20} />
            </button>

            <h2 className="text-xl font-bold flex items-center gap-2 mb-4">
              <Server className="text-primary" />
              服务器连接诊断
            </h2>

            <div className="space-y-4 text-sm text-gray-300">
              <div className="bg-black/30 p-3 rounded-lg border border-white/5">
                <p className="flex justify-between mb-1">
                  <span className="text-gray-400">当前状态:</span>
                  {serverStatus === 'online' && <span className="text-green-400 font-bold">连接正常</span>}
                  {serverStatus === 'cors_error' && <span className="text-yellow-400 font-bold">CORS 跨域错误</span>}
                  {serverStatus === 'offline' && <span className="text-red-400 font-bold">无法连接</span>}
                </p>
                <p className="flex justify-between">
                  <span className="text-gray-400">API 地址:</span>
                  <span className="font-mono text-xs opacity-70 truncate max-w-[200px]">{COMFY_API_URL}</span>
                </p>
              </div>

              {serverStatus === 'cors_error' && (
                <div className="bg-yellow-500/10 border border-yellow-500/20 p-4 rounded-lg">
                  <h3 className="text-yellow-200 font-bold mb-2 flex items-center gap-2">
                    <AlertTriangle size={16} />
                    发现 CORS 跨域问题
                  </h3>
                  <p className="mb-2">您的服务器已启动，但浏览器阻止了前端网页的访问。这是因为 ComfyUI 默认不允许跨域请求。</p>
                  <p className="mb-2 font-semibold text-white">解决方法：</p>
                  <p>请在启动 ComfyUI 的命令中添加以下参数：</p>
                  <code className="block bg-black/50 p-2 rounded mt-2 text-yellow-100 font-mono select-all">
                    --enable-cors-header *
                  </code>
                  <p className="mt-2 text-xs opacity-70">
                    示例：<code>python main.py --listen --enable-cors-header *</code>
                  </p>
                </div>
              )}

              {mixedContentWarning && (
                <div className="bg-orange-500/10 border border-orange-500/20 p-4 rounded-lg">
                  <h3 className="text-orange-200 font-bold mb-2 flex items-center gap-2">
                    <Lock size={16} />
                    混合内容错误 (Mixed Content)
                  </h3>
                  <p>您正在使用 HTTPS 访问网页，但服务器是 HTTP。浏览器会强制拦截请求。</p>
                  <p className="mt-2 font-semibold text-white">解决方法：</p>
                  <ul className="list-disc list-inside mt-1 space-y-1">
                    <li>使用 HTTP 协议访问此网页 (将地址栏 https:// 改为 http://)</li>
                    <li>或者为 ComfyUI 服务器配置 SSL 证书</li>
                  </ul>
                </div>
              )}

              {serverStatus === 'offline' && !mixedContentWarning && (
                <div>
                  <p>无法连接到服务器，请稍后再试。</p>
                </div>
              )}
            </div>

            <div className="mt-6 flex justify-end">
              <button onClick={() => setShowHelpModal(false)} className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-white transition-colors">
                关闭
              </button>
            </div>
          </div>
        </div>
      )}

      {/* AI Prompt Chain Modal */}
      {showAIPromptModal && (
        <div className="fixed inset-0 z-[200] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
          <div className="bg-surface border border-white/10 rounded-2xl shadow-2xl max-w-3xl w-full max-h-[85vh] flex flex-col animate-in zoom-in-95 duration-300">
            <div className="p-4 border-b border-white/5 flex items-center justify-between shrink-0">
              <h2 className="text-lg font-bold text-white flex items-center gap-2">
                <Brain size={20} className="text-primary" />
                {t.chainOfThought.title}
              </h2>
              <button onClick={() => setShowAIPromptModal(false)} className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white transition-colors">
                <X size={20} />
              </button>
            </div>

            <div className="p-4 overflow-y-auto flex-1 custom-scrollbar">
              <p className="text-sm text-gray-400 mb-4">
                {t.chainOfThought.description}
              </p>
              <pre id="ai-prompt-content" className="bg-darker border border-white/10 rounded-xl p-4 text-xs text-gray-300 whitespace-pre-wrap font-mono leading-relaxed overflow-x-auto">
                {t.chainOfThought.promptContent}
              </pre>
            </div>

            <div className="p-4 border-t border-white/5 flex justify-end gap-3 shrink-0">
              <button
                onClick={() => {
                  const text = document.querySelector('#ai-prompt-content')?.textContent || '';
                  navigator.clipboard.writeText(text);
                  setCopiedAIPrompt(true);
                  setTimeout(() => setCopiedAIPrompt(false), 2000);
                }}
                className="px-4 py-2 bg-primary/20 hover:bg-primary/30 text-primary rounded-lg transition-colors flex items-center gap-2"
              >
                {copiedAIPrompt ? <Check size={16} /> : <Copy size={16} />}
                {copiedAIPrompt ? t.chainOfThought.copied : t.chainOfThought.copyPrompt}
              </button>
              <button onClick={() => setShowAIPromptModal(false)} className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg text-white transition-colors">
                {t.chainOfThought.close}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-darker/80 backdrop-blur-lg border-b border-white/5 h-16 flex items-center justify-between px-4 lg:px-12">
        <div className="flex items-center gap-2 sm:gap-3">
          {/* Mobile Menu Button (Left) */}
          <button
            onClick={() => setShowMobileSettings(true)}
            className="lg:hidden p-1.5 -ml-1 text-gray-400 hover:text-white"
          >
            <Settings size={18} />
          </button>

          <div className="w-6 h-6 sm:w-8 sm:h-8 rounded-md sm:rounded-lg bg-gradient-to-br from-primary to-secondary flex items-center justify-center shadow-lg shadow-primary/20">
            <Sparkles size={14} className="text-white sm:hidden" />
            <Sparkles size={18} className="text-white hidden sm:block" />
          </div>
          <div className="hidden sm:block">
            <h1 className="font-bold text-lg tracking-tight text-white">{t.nav.title}</h1>
            <p className="text-[10px] text-gray-400 uppercase tracking-widest font-semibold">{t.nav.subtitle}</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <button
            onClick={() => setShowAIAssistant(true)}
            className="text-sm text-gray-400 hover:text-white transition-colors hidden sm:flex items-center gap-1.5 bg-primary/10 hover:bg-primary/20 px-3 py-1.5 rounded-lg border border-primary/20"
            title={t.nav.aiAssistant}
          >
            <Brain size={16} className="text-primary" />
            <span className="text-primary">{t.nav.aiAssistant}</span>
          </button>
          <button
            onClick={() => setShowAIPromptModal(true)}
            className="text-sm text-gray-400 hover:text-white transition-colors hidden sm:flex items-center gap-1.5"
            title={t.nav.chainOfThought}
          >
            {t.nav.chainOfThought}
          </button>
          <a href="https://ai.feishu.cn/wiki/P3sgwUUjWih8ZWkpr0WcwXSMnTb" target="_blank" rel="noopener noreferrer" className="text-sm text-gray-400 hover:text-white transition-colors hidden sm:block">{t.nav.guideAndDocs}</a>

          <Link to="/standard" className="text-sm text-gray-400 hover:text-white transition-colors hidden sm:flex items-center gap-1.5 border border-white/20 px-3 py-1.5 rounded-lg hover:border-primary">
            <span className="hidden lg:inline">Switch to </span>Standard Mode
          </Link>

          <div className="hidden sm:block">
            <LanguageSwitcher />
          </div>
          <div className="h-4 w-px bg-white/10 hidden sm:block"></div>

          {/* Mobile Quick Action Icons */}
          <div className="flex items-center gap-1 sm:hidden">
            <button
              onClick={() => setShowAIAssistant(true)}
              className="p-1.5 text-primary hover:bg-primary/20 rounded-lg"
              title={t.nav.aiAssistant}
            >
              <Brain size={18} />
            </button>
            <button
              onClick={() => setShowAIPromptModal(true)}
              className="p-1.5 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg"
              title={t.nav.chainOfThought}
            >
              <Lightbulb size={18} />
            </button>
            <a
              href="https://ai.feishu.cn/wiki/P3sgwUUjWih8ZWkpr0WcwXSMnTb"
              target="_blank"
              rel="noopener noreferrer"
              className="p-1.5 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg"
              title={t.nav.guideAndDocs}
            >
              <BookOpen size={18} />
            </a>

            {/* Standard Mode Switch (Mobile) */}
            <Link
              to="/standard"
              className="p-1.5 text-purple-400 hover:text-purple-300 hover:bg-white/10 rounded-lg"
              title="Switch to Standard Mode"
            >
              <LayoutTemplate size={18} />
            </Link>

            <LanguageSwitcher compact />
          </div>

          {renderServerStatus()}

          {/* Mobile History Button (Right) */}
          <button
            onClick={() => setShowMobileHistory(true)}
            className="lg:hidden p-2 -mr-2 text-gray-400 hover:text-white"
          >
            <History size={20} />
          </button>
        </div>
      </header>

      {/* Mobile Drawers */}
      <MobileDrawer
        isOpen={showMobileSettings}
        onClose={() => setShowMobileSettings(false)}
        title={t.mobileDrawer.configAndPrompt}
        position="left"
      >
        <div className="space-y-6 pb-8">
          <SettingsPanel settings={settings} onChange={setSettings} />
          <div className="border-t border-white/5 pt-6">
            <h3 className="text-sm font-bold text-gray-400 mb-4 px-2">{t.promptBuilder.simpleMode}</h3>
            <PromptArea
              activeTab={activeTab}
              setActiveTab={setActiveTab}
              characters={characters}
              setCharacters={setCharacters}
              general={general}
              setGeneral={setGeneral}
              builderOutput={builderOutput}
              setBuilderOutput={setBuilderOutput}
              rawPrompt={rawPrompt}
              setRawPrompt={setRawPrompt}
              previewingHistoryPrompt={previewingHistoryPrompt}
            />
          </div>
        </div>
      </MobileDrawer>

      <MobileDrawer
        isOpen={showMobileHistory}
        onClose={() => setShowMobileHistory(false)}
        title={t.history.generationHistory}
        position="right"
      >
        <HistoryGallery
          history={history}
          selectedId={selectedHistoryId || undefined}
          onSelect={(img) => {
            setCurrentImage(img.url);
            setSelectedHistoryId(img.id);
            setPreviewingHistoryPrompt(img.prompt);
            setShowMobileHistory(false); // Close drawer on select
          }}
          onUpscale={handleUpscaleImage}
          upscalingId={upscalingId}
        />
      </MobileDrawer>

      {/* Main Content */}
      {/* Desktop: Fixed height layout with independent scrolling */}
      <main className="hidden lg:flex fixed top-16 left-0 right-0 bottom-0 py-4 pl-4 pr-4 gap-4">

        {/* Left Column: Controls - Independent Scroll */}
        <div className="w-[540px] flex flex-col bg-surface/30 rounded-2xl border border-white/5 overflow-hidden">
          <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
            {/* Warning Banner for Mixed Content */}
            {mixedContentWarning && (
              <div className="mb-4 bg-orange-500/10 border border-orange-500/20 rounded-xl p-3 flex items-start gap-2 text-orange-200 cursor-pointer hover:bg-orange-500/15 transition-colors text-sm" onClick={() => setShowHelpModal(true)}>
                <Lock className="shrink-0 mt-0.5" size={16} />
                <div>
                  <h3 className="font-bold text-orange-100 text-xs mb-1">{t.serverDiag.mixedContentWarning}</h3>
                  <p className="text-xs opacity-90">{t.serverDiag.clickForDetails}</p>
                </div>
              </div>
            )}

            {/* Prompt Input Area */}
            <PromptArea
              activeTab={activeTab}
              setActiveTab={setActiveTab}
              characters={characters}
              setCharacters={setCharacters}
              general={general}
              setGeneral={setGeneral}
              builderOutput={builderOutput}
              setBuilderOutput={setBuilderOutput}
              rawPrompt={rawPrompt}
              setRawPrompt={setRawPrompt}
              previewingHistoryPrompt={previewingHistoryPrompt}
            />

            {/* Settings */}
            <div className="mt-4">
              <SettingsPanel settings={settings} onChange={setSettings} />
            </div>
          </div>
        </div>

        {/* Center Column: Image Display + Generate Button */}
        <div className="flex-1 flex flex-col gap-4">

          {/* Main Image Stage */}
          <div className="flex-1 min-h-[600px] bg-black/40 rounded-3xl border border-white/5 overflow-hidden relative flex items-center justify-center group">

            {/* Background Pattern */}
            <div className="absolute inset-0 opacity-20"
              style={{
                backgroundImage: 'radial-gradient(#475569 1px, transparent 1px)',
                backgroundSize: '20px 20px'
              }}
            ></div>

            {currentImage ? (
              <div className="relative w-full h-full p-4 animate-in fade-in zoom-in duration-500 flex items-center justify-center">
                <img
                  src={currentImage}
                  alt="Result"
                  className="max-w-full max-h-full object-contain rounded-lg shadow-2xl shadow-black"
                />
                <div className="absolute top-8 right-8 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button
                    onClick={async () => {
                      try {
                        const response = await fetch(currentImage);
                        const blob = await response.blob();
                        const url = window.URL.createObjectURL(blob);
                        const a = document.createElement('a');
                        a.href = url;
                        a.download = `newbie_${Date.now()}.png`;
                        document.body.appendChild(a);
                        a.click();
                        document.body.removeChild(a);
                        window.URL.revokeObjectURL(url);
                      } catch {
                        // Fallback: open in new tab if download fails
                        window.open(currentImage, '_blank');
                      }
                    }}
                    className="bg-black/50 hover:bg-black/70 text-white p-2 rounded-lg backdrop-blur-md transition-colors"
                    title={t.history.download}
                  >
                    <Download size={20} />
                  </button>
                </div>
              </div>
            ) : (
              <div className="text-center p-8">
                {status === GenerationStatus.GENERATING ? (
                  <div className="space-y-4">
                    <div className="relative w-24 h-24 mx-auto">
                      <div className="absolute inset-0 rounded-full border-4 border-primary/20"></div>
                      <div className="absolute inset-0 rounded-full border-4 border-primary border-t-transparent animate-spin"></div>
                      <Sparkles className="absolute inset-0 m-auto text-primary animate-pulse" size={32} />
                    </div>
                    <p className="text-gray-400 animate-pulse">{t.status.drawingMasterpiece}</p>
                  </div>
                ) : (
                  <div className="space-y-2 opacity-50">
                    <div className="w-20 h-20 bg-white/5 rounded-2xl mx-auto flex items-center justify-center mb-4">
                      <ImageIcon size={32} className="text-gray-500" />
                    </div>
                    <p className="text-gray-400 font-medium">{t.status.readyToGenerate}</p>
                    <p className="text-sm text-gray-600">{t.status.readyToGenerateHint}</p>
                  </div>
                )}
              </div>
            )}

            {/* History Prompt Preview Banner */}
            {previewingHistoryPrompt && (
              <div className="absolute bottom-4 left-4 right-4 bg-surface/95 backdrop-blur-md rounded-xl border border-primary/30 p-4 animate-in slide-in-from-bottom duration-300">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-gray-400">{t.history.historyPreview}</span>
                  <button
                    onClick={() => {
                      setPreviewingHistoryPrompt(null);
                      setSelectedHistoryId(null);
                    }}
                    className="text-gray-500 hover:text-white text-xs"
                  >
                    {t.common.cancel}
                  </button>
                </div>
                <p className="text-xs text-gray-300 line-clamp-2 mb-3">{previewingHistoryPrompt.substring(0, 150)}...</p>
                <div className="flex gap-2">
                  <button
                    onClick={() => {
                      // TODO: Parse XML and fill builder fields
                      // For now, we just show in raw mode
                      setActiveTab('raw');
                    }}
                    className="flex-1 py-2 text-sm bg-white/10 hover:bg-white/20 rounded-lg transition-colors"
                  >
                    {t.history.viewPrompt}
                  </button>
                  <button
                    onClick={() => {
                      // Clear preview and keep current prompt
                      setPreviewingHistoryPrompt(null);
                      setSelectedHistoryId(null);
                    }}
                    className="flex-1 py-2 text-sm bg-primary/20 hover:bg-primary/30 text-primary rounded-lg transition-colors"
                  >
                    {t.history.useCurrentPrompt}
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Generate Button - Desktop */}
          <div className="flex items-center gap-4">
            <button
              onClick={handleGenerate}
              disabled={status === GenerationStatus.GENERATING || status === GenerationStatus.PREPARING || status === GenerationStatus.QUEUED || !prompt || mixedContentWarning || serverStatus !== 'online'}
              className={`flex-1 py-4 rounded-xl font-bold text-white shadow-lg transition-all transform active:scale-95 flex items-center justify-center gap-2
                        ${(status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED || mixedContentWarning || serverStatus !== 'online')
                  ? 'bg-gray-700 cursor-not-allowed grayscale'
                  : 'bg-gradient-to-r from-primary to-secondary hover:shadow-primary/25 hover:brightness-110'
                }
                    `}
            >
              {status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED ? (
                <>
                  <span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
                  {status === GenerationStatus.QUEUED ? t.common.recovering : t.common.generating}
                </>
              ) : (
                <>
                  <Zap size={20} className="fill-white" />
                  {t.common.generate}
                </>
              )}
            </button>
            {errorMsg && (
              <div className="p-3 bg-red-500/10 border border-red-500/20 rounded-lg flex items-center gap-2 text-red-400 text-xs max-w-xs">
                <AlertTriangle size={14} className="shrink-0" />
                <span className="truncate">{errorMsg}</span>
              </div>
            )}
          </div>
          {/* 生成中提示 */}
          {(status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED) && (
            <p className="text-xs text-gray-500 text-center mt-2">
              {t.status.canLeavePageTip}
            </p>
          )}
        </div>

        {/* Right Column: History - Independent Scroll */}
        <div className="w-48 flex flex-col bg-surface/30 rounded-2xl border border-white/5 overflow-hidden">
          <div className="p-3 border-b border-white/5 shrink-0">
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider">{t.history.title}</h3>
          </div>
          <div className="flex-1 overflow-y-auto custom-scrollbar">
            <HistoryGallery
              history={history}
              selectedId={selectedHistoryId || undefined}
              onSelect={(img) => {
                setCurrentImage(img.url);
                setSelectedHistoryId(img.id);
                setPreviewingHistoryPrompt(img.prompt);
              }}
              onUpscale={handleUpscaleImage}
              upscalingId={upscalingId}
            />
          </div>
        </div>
      </main>

      {/* Mobile: Scrollable layout */}
      <main className="lg:hidden pt-20 pb-24 px-4">
        {/* Warning Banner for Mixed Content - Mobile */}
        {mixedContentWarning && (
          <div className="mb-4 bg-orange-500/10 border border-orange-500/20 rounded-xl p-3 flex items-start gap-2 text-orange-200 cursor-pointer hover:bg-orange-500/15 transition-colors text-sm" onClick={() => setShowHelpModal(true)}>
            <Lock className="shrink-0 mt-0.5" size={16} />
            <div>
              <h3 className="font-bold text-orange-100 text-xs mb-1">{t.serverDiag.mixedContentWarning}</h3>
              <p className="text-xs opacity-90">{t.serverDiag.clickForDetails}</p>
            </div>
          </div>
        )}

        {/* Mobile Image Display */}
        <div className="min-h-[400px] bg-black/40 rounded-2xl border border-white/5 overflow-hidden relative flex items-center justify-center">
          <div className="absolute inset-0 opacity-20"
            style={{
              backgroundImage: 'radial-gradient(#475569 1px, transparent 1px)',
              backgroundSize: '20px 20px'
            }}
          ></div>

          {currentImage ? (
            <div className="relative w-full h-full p-4 flex items-center justify-center">
              <img
                src={currentImage}
                alt="Result"
                className="max-w-full max-h-full object-contain rounded-lg shadow-2xl shadow-black"
              />
            </div>
          ) : (
            <div className="text-center p-8">
              {status === GenerationStatus.GENERATING ? (
                <div className="space-y-4">
                  <div className="relative w-20 h-20 mx-auto">
                    <div className="absolute inset-0 rounded-full border-4 border-primary/20"></div>
                    <div className="absolute inset-0 rounded-full border-4 border-primary border-t-transparent animate-spin"></div>
                    <Sparkles className="absolute inset-0 m-auto text-primary animate-pulse" size={28} />
                  </div>
                  <p className="text-gray-400 animate-pulse text-sm">{t.status.drawingMasterpiece}</p>
                </div>
              ) : (
                <div className="space-y-2 opacity-50">
                  <div className="w-16 h-16 bg-white/5 rounded-2xl mx-auto flex items-center justify-center mb-4">
                    <ImageIcon size={28} className="text-gray-500" />
                  </div>
                  <p className="text-gray-400 font-medium text-sm">{t.status.readyToGenerate}</p>
                  <p className="text-xs text-gray-600">{t.status.clickSettingsToConfig}</p>
                </div>
              )}
            </div>
          )}
        </div>
      </main>

      {/* Mobile Bottom Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-darker/90 backdrop-blur border-t border-white/10 lg:hidden z-40 flex flex-col gap-2">
        {errorMsg && (
          <div className="p-2 bg-red-500/10 border border-red-500/20 rounded text-red-400 text-xs truncate">
            {errorMsg}
          </div>
        )}
        <button
          onClick={handleGenerate}
          disabled={status === GenerationStatus.GENERATING || status === GenerationStatus.PREPARING || status === GenerationStatus.QUEUED || !prompt || mixedContentWarning || serverStatus !== 'online'}
          className={`w-full py-3 rounded-xl font-bold text-white shadow-lg transition-all transform active:scale-95 flex items-center justify-center gap-2
                    ${(status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED || mixedContentWarning || serverStatus !== 'online')
              ? 'bg-gray-700 cursor-not-allowed grayscale'
              : 'bg-gradient-to-r from-primary to-secondary hover:shadow-primary/25 hover:brightness-110'
            }
                `}
        >
          {status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED ? (
            <>
              <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"></span>
              {status === GenerationStatus.QUEUED ? t.common.recovering : t.common.generating}
            </>
          ) : (
            <>
              <Zap size={18} className="fill-white" />
              {t.common.generate}
            </>
          )}
        </button>
        {/* 生成中提示 - 移动端 */}
        {(status === GenerationStatus.GENERATING || status === GenerationStatus.QUEUED) && (
          <p className="text-xs text-gray-500 text-center">
            {t.status.canLeavePageTipShort}
          </p>
        )}
      </div>

      {/* AI Assistant */}
      <AIAssistant
        isOpen={showAIAssistant}
        onClose={() => setShowAIAssistant(false)}
        onFillBuilder={(chars, gen) => {
          setCharacters(chars);
          setGeneral(gen);
          setActiveTab('builder');
        }}
        onFillRaw={(xml) => {
          setRawPrompt(xml);
          setActiveTab('raw');
        }}
      />
    </div>
  );
};

export default App;